name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

      # Trigger Packagist update after release is created
      - name: Update Packagist
        if: ${{ steps.release.outputs.release_created }}
        run: |
          curl -XPOST -H'content-type:application/json' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -d'{"repository":{"url":"https://packagist.org/packages/constructions-incongrues/flarum-lite-youtube"}}'